# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

image: maven:3.8.6-openjdk-21

stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  API_BASE_URL: "https://cde-api.test.briodev.ru/"

cache:
  paths:
    - .m2/repository/

run-tests:
  stage: test
  script:
    - mvn clean test
    - mvn allure:report # Генерация Allure-отчета
  artifacts:
    paths:
      - target/surefire-reports/
      - target/allure-results/
      - target/site/allure-maven-plugin/ # Папка с Allure-отчетом
    expire_in: 1 week

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r target/site/allure-maven-plugin/* public/ # Копируем Allure-отчет в папку public
  artifacts:
    paths:
      - public
  only:
    - main # Запускать только для ветки main

notifications:
  email:
    recipients:
      - mrazetdinov@briogroup.ru
    on_success: always
    on_failure: always
    on_pipeline_failure: always
    