stages:
  - test
  - deploy
  - pages  # Добавляем отдельный этап для Pages

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  API_BASE_URL: "https://cde-api.test.briodev.ru/"
  CI_DEBUG_TRACE: "true"

cache:
  paths:
    - .m2/repository/

run-tests:
  image: maven:3.9.9-amazoncorretto-21
  stage: test
  tags:
    - docker-on-host
  script:
    - mvn clean test
    - mvn allure:report
  artifacts:
    paths:
      - target/allure-results/  # Важно: сохраняем сырые данные Allure
    expire_in: 1 week

generate-allure:
  stage: deploy
  image: maven:3.9.9-amazoncorretto-21
  tags:
    - docker-on-host
  script:
    - mvn allure:report  # Генерируем финальный HTML-отчет
    - mkdir -p public/allure
    - cp -r target/site/allure-maven-plugin/* public/allure/
  artifacts:
    paths:
      - public/allure/
  needs: ["run-tests"]  # Зависит от этапа run-tests

pages:
  stage: pages
  script:
    - echo "Allure report will be available at $CI_PAGES_URL/allure"
  artifacts:
    paths:
      - public  # GitLab автоматически развернет содержимое public на Pages
  only:
    - master