stages:
  - test
  - deploy

run-tests:
  stage: test
  image: maven:3.9.9-amazoncorretto-21
  script:
    - mvn clean test
    - mvn allure:report  # Генерируем отчет
  artifacts:
    paths:
      - target/allure-results/  # Сырые данные Allure (обязательно!)
    reports:
      allure_report:  # Специальный тип артефакта для GitLab
        - target/allure-results/  # Путь к результатам
    expire_in: 1 week

pages:
  stage: deploy
  script:
    - mvn allure:report  # Повторная генерация HTML
    - mkdir -p public
    - cp -r target/site/allure-maven-plugin/* public/  # Для GitLab Pages
  artifacts:
    paths:
      - public
  only:
    - master